Business Understanding
        ↓
Data Collection
        ↓
Dataset Understanding
        ↓
Data Cleaning
        ↓
Handle Missing Values
        ↓
Handle Outliers (if required)
        ↓
Exploratory Data Analysis (EDA)
        ↓
Feature Engineering (if required)
        ↓
Encoding (if categorical data)
        ↓
Define Features (X) and Target (y)
        ↓
Train-Validation-Test Split
        ↓
Feature Scaling (Normalization / Standardization)
        ↓
Convert to Tensors
        ↓
Create Dataset & DataLoader
        ↓
Design Neural Network Architecture
        ↓
Choose Loss Function
        ↓
Choose Optimizer
        ↓
Training Loop
        ↓
Validation
        ↓
Hyperparameter Tuning
        ↓
Model Evaluation
        ↓
Save Trained Model
        ↓
Inference / Prediction
        ↓
Deployment
        ↓
GitHub + README

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os 
import pandas as pd

pd.set_option("display.max_columns", None) #because dataset is huge

In [20]:
data = pd.read_csv(r"C:\Users\shobh\OneDrive\Attachments\Documents\Desktop\py\Telco-Customer-Churn.csv")
pd.set_option("display.max_columns", None)

df = pd.DataFrame(data)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [34]:
# we need to change dtype of Total charges 

df["MonthlyCharges"] = df["MonthlyCharges"].astype(int)

In [21]:
#dataset understanding

df.sample(3)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
4087,3847-BAERP,Female,0,No,No,10,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,20.90,247,No
6007,2724-FJDYW,Male,0,No,Yes,39,No,No phone service,DSL,No,No,Yes,Yes,Yes,Yes,One year,No,Bank transfer (automatic),54.85,2191.7,No
5033,7298-IZWLY,Female,0,No,No,1,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.40,19.4,No

# columns we will use for training 

| Column Name      |
| ---------------- |
| gender           |
| SeniorCitizen    |
| Partner          |
| Dependents       |
| tenure           |
| PhoneService     |
| MultipleLines    |
| InternetService  |
| OnlineSecurity   |
| OnlineBackup     |
| DeviceProtection |
| TechSupport      |
| StreamingTV      |
| StreamingMovies  |
| Contract         |
| PaperlessBilling |
| PaymentMethod    |
| MonthlyCharges   |
| TotalCharges     |

In [8]:
df.nunique()

customerID          7043
gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [11]:
#data cleaning

df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

no duplcate rows and no null values found

# leaving eda for you claude 

add meaning ful observtion using html markdown clourful texts and higlisghts and bold charters and various fonts with professional divs

In [22]:
pd.set_option("display.max_columns", None)
df.sample(3)


# columns to scale : 

# tenure
# MonthlyCharges
# TotalCharges

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
3004,3801-HMYNL,Male,0,Yes,Yes,1,Yes,No,Fiber optic,No,No,No,No,Yes,Yes,Month-to-month,No,Mailed check,89.15,89.15,Yes
3718,8468-EHYJA,Female,0,Yes,No,57,Yes,Yes,Fiber optic,Yes,No,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,5497.05,No
3174,6968-MHOMU,Male,0,Yes,No,58,No,No phone service,DSL,No,No,No,No,Yes,Yes,One year,Yes,Credit card (automatic),45.00,2689.35,No

In [45]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [46]:
# feature scaling 

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[['tenure']] = scaler.fit_transform(df[['tenure']])
df[['MonthlyCharges']] = scaler.fit_transform(df[['MonthlyCharges']])
df[['TotalCharges']] = scaler.fit_transform(df[['TotalCharges']])

| Column to Encode          |
| ------------------------- |
| `gender`                  |
| `Partner`                 |
| `Dependents`              |
| `PhoneService`            |
| `MultipleLines`           |
| `InternetService`         |
| `OnlineSecurity`          |
| `OnlineBackup`            |
| `DeviceProtection`        |
| `TechSupport`             |
| `StreamingTV`             |
| `StreamingMovies`         |
| `Contract`                |
| `PaperlessBilling`        |
| `PaymentMethod`           |
| `Churn` *(target column)* |

In [51]:
df.drop(columns = 'customerID',inplace = True)

In [52]:
#enocding 


from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()


binary_cols = [
    "gender",
    "Partner",
    "Dependents",
    "PhoneService",
    "PaperlessBilling",
    "Churn"
]

for col in binary_cols:
    df[col] = le.fit_transform(df[col])


multi_cols = [
    "MultipleLines",
    "InternetService",
    "OnlineSecurity",
    "OnlineBackup",
    "DeviceProtection",
    "TechSupport",
    "StreamingTV",
    "StreamingMovies",
    "Contract",
    "PaymentMethod"
]


df = pd.get_dummies(df, columns=multi_cols, drop_first=True)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,MultipleLines_No phone service,MultipleLines_Yes,InternetService_Fiber optic,InternetService_No,OnlineSecurity_No internet service,OnlineSecurity_Yes,OnlineBackup_No internet service,OnlineBackup_Yes,DeviceProtection_No internet service,DeviceProtection_Yes,TechSupport_No internet service,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
1967,1,0,0,0,1.49154,1,1,0.086044,1.355835,1,False,True,False,False,False,True,False,True,False,True,False,True,False,False,False,True,True,False,True,False,False

In [56]:
df_ready = df.copy()


df_ready.to_csv(r"C:\Users\shobh\Downloads\AI and DATA SCIENCE\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀 (𝗧𝗮𝗯𝘂𝗹𝗮𝗿 𝗗𝗮𝘁𝗮)\Customer Churn Prediction\data\cleaned_and_scaled_dataset.csv")

In [58]:
#define X and y 

X = df.drop(columns = 'Churn')

y = df['Churn']

In [ ]:
#train - test split