# 🧠 NLP + Machine Learning Project Workflow

Business Understanding
        ↓
Data Collection
        ↓
Dataset Understanding
        ↓
Data Cleaning
        ↓
Exploratory Data Analysis (EDA)
        ↓
Text Preprocessing
        ↓
Train / Validation / Test Split
        ↓
Feature Extraction
(Bag of Words / TF-IDF)
        ↓
Create Training Data
        ↓
Choose ML Model
        ↓
Choose Evaluation Metrics
        ↓
Training
        ↓
Validation
        ↓
Hyperparameter Tuning (Optional)
        ↓
Model Evaluation
        ↓
Error Analysis
        ↓
Save Trained Model
        ↓
Inference / Prediction
        ↓
Deployment
(Streamlit / API)
        ↓
GitHub + README

#### <mark>Project Goal

Build a **Twitter Sentiment Analysis** system that predicts whether a tweet is:

* 🟢 **Good**
* 🔴 **Bad**
* ⚪ **Neutral**

**Goal:** Automatically understand people's opinions from large amounts of tweets.

**End Result:**

`Tweet → NLP Processing → ML Model → Sentiment`

**Use:** Help businesses analyze public opinion about their products, brands, campaigns, or topics.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\rohit\Downloads\AI and Data Science\𝗡𝗟𝗣 𝘄𝗶𝘁𝗵 𝗠𝗮𝗰𝗵𝗶𝗻𝗲 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴\ChatGPT Sentiment Analysis\data\file.csv")

pd.set_option("display.max_colwidth", None)

df.head()

,Unnamed: 0,tweets,labels
0,0,ChatGPT: Optimizing Language Models for Dialogue https://t.co/K9rKRygYyn @OpenAI,neutral
1,1,"Try talking with ChatGPT, our new AI system which is optimized for dialogue. Your feedback will help us improve it. https://t.co/sHDm57g3Kr",good
2,2,ChatGPT: Optimizing Language Models for Dialogue https://t.co/GLEbMoKN6w #AI #MachineLearning #DataScience #ArtificialIntelligence\n\nTrending AI/ML Article Identified &amp; Digested via Granola; a Machine-Driven RSS Bot by Ramsey Elbasheer https://t.co/RprmAXUp34,neutral
3,3,"THRILLED to share that ChatGPT, our new model optimized for dialog, is now public, free, and accessible to everyone. https://t.co/dyvtHecYbd https://t.co/DdhzhqhCBX https://t.co/l8qTLure71",good
4,4,"As of 2 minutes ago, @OpenAI released their new ChatGPT. \n\nAnd you can use it right now 👇 https://t.co/VyPGPNw988 https://t.co/cSn5h6h1M1",bad

In [3]:
df.columns

Index(['Unnamed: 0', 'tweets', 'labels'], dtype='str')

In [4]:
df.drop(columns = 'Unnamed: 0',inplace = True)

# Data Cleaning

In [5]:
df.isnull().sum()

tweets    0
labels    0
dtype: int64

In [6]:
df['labels'].nunique()

3

In [7]:
df['labels'].value_counts()

labels
bad        107796
good        56011
neutral     55487
Name: count, dtype: int64

In [8]:
df['labels'].unique()

<ArrowStringArray>
['neutral', 'good', 'bad']
Length: 3, dtype: str

In [9]:
#providing indexes to all labels 

labels = ['neutral', 'good', 'bad']

labels

['neutral', 'good', 'bad']

In [10]:
label_number = {}

i = 0

for label in labels:
    label_number[label] = i
    i = i + 1

In [11]:
label_number

{'neutral': 0, 'good': 1, 'bad': 2}

In [12]:
#now apply these changes into the original df

df['labels'] = df['labels'].map(label_number)

In [13]:
#lets verify

df.sample(3)

,tweets,labels
190658,"Hey ChatGPT worriers - wealthy univs have people who will heavily revise the grant proposals for you. Is that inequitable, if not unethical. How about students who write major parts of proposal and are not even a PI or senior personnel. @OpenAI @EnglishOER",2
75310,Just made my first $1000 using #ChatGPT 😏 I think I will keep this strategy to myself for a lil while #cheatcode 😝,2
190571,"Listen I don't do all this Xmas shit but I have a gift for yall! My discord community ready buying AI sector crypro projects a few months ago. With AI software like ChatGpt and Midjourney taking off, expect this sector to benefit in the next bull maket. #NFA #DYOR https://t.co/xndJaHf97S",1

In [14]:
#now labels work is done we will start working on tweets as well 


#first of all converting everything into lowercase 

df['tweets'] = df['tweets'].apply(lambda x : x.lower())

In [15]:
df.sample()

,tweets,labels
131426,i'm taking advice from an ai and it's actually better than me...what the f-\n\n#chatgpt3 #chatgpt #artificialintelligence #ai https://t.co/x2qkni7umu,0

In [16]:
# step 2 : clean punctuation marks

punctuation_marks = [
    ".",
    ",",
    "?",
    "!",
    ";",
    ":",
    "-",
    "—",
    "–",
    "'",
    '"',
    "(",
    ")",
    "[",
    "]",
    "{",
    "}",
    "...",
    "/",
    "\\"
]


print(*punctuation_marks)

. , ? ! ; : - — – ' " ( ) [ ] { } ... / \

In [17]:
import string
import builtins

def remove_punc(txt):
    return txt.translate(builtins.str.maketrans('', '', string.punctuation))

df['tweets'] = df['tweets'].apply(remove_punc)

# maketrans() creates a translation table for str.translate().
# str.maketrans(from, to, delete)

In [18]:
# 3rd step is remove number but the project may contain tweets like i waited for 3 hours , 5 star review , 8/10 may can conflict later

In [19]:
#Remove URL's and link 

df.sample(12)

,tweets,labels
174595,chatgpt ftw httpstcootdnol89bo,0
68397,stack overflow bans answers generated by chartgpt nhttpstcob16vh6s68o,2
135672,can we trust the chatbots ainchatbotsnnhttpstcobbafswamek,1
50762,it was necessary i asked chatgpt to write a c code and it gave a very convincing answer but after checking carefully i found several syntax errors httpstcoawenckp5zc via verge,2
201461,💭 chatgpt is a variant of the popular language model gpt that has been specifically designed to perform well in chatbot scenarios developed by openai chatgpt allows developers to build chatbots that can hold more natural and engaging conversations with users httpstcogygn6rr981,1
79105,how long until we can ask ai to make a better ai nnor ask chatgpt to make a better chatgpt,1
144373,it doesnt mention a fever but its still pretty good chatgpt cowbell snl httpstcoi5t7vsibz0,1
36247,i can’t stop playing with chatgpt brother what is this 🫡,2
133925,trending in philippinesnnmiss international 2022njenna ortegan2022 fifa world cupnchatgptnnwikipedia,2
213960,imagine everyone knowsnhow to set up a walletnhow to buymint nftsnhow to contribute to a dao nhow to run a virtual gallery event in the metaverse etcnthe mainstream conversation wont be about speculating on crypto assets then itll be about building chatgpt web3,1
216250,having issues with my jwt web tokens and my coding buddy openai chatgpt is helping me debug👏ndebug javascript react webdeveloper fullstack opentowork httpstcokzxksnrmmq,0
76044,the implications of chatgpt are actually enormous its capacity spirals out in all directions imagine its capacity to improve translations for example one could ask it for each word and phrase to consult hundreds of different reference materials as well as spoken language,0

In [20]:
def remove_link(txt):
    return txt.split('https')[0].strip()

df['tweets'] = df['tweets'].apply(remove_link)

In [21]:
df.sample(7)

,tweets,labels
72889,🤔 have you ever submitted to ploscompbiol ❓i am asking because we have a paper submitted in that journal since september yes september and it is still in the hands of the editor without being sent for external review a guinness record❗️ they need chatgpt up there❗️,0
188298,the chatbots are coming for google chatbot chatbots digital via,2
121546,chatgpt has mastered the confidence trick and thats a terrible look for ai its very good and thats very bad ai ml 12 dec 2022 44,2
126053,been trying out chatgpt i do find it funny that i have to declare that i am not a robot before i can play with the robot,1
126590,the trick is knowing what belongs to google search and what belongs to chatgpt and not forgetting to be courteousit somehow gets you more info,0
108883,the year is 2030 and the elite are those that got early unlimited access to chatgpt,2
168511,stackoverflow is dead had a student post a there as he’s learning first comment began “obviously…” followed by condescention he was too scared to even reply to the guy copied the same question to chatgpt same answer with politeness long live the gpt and be nice to kids,2

In [22]:
#link removed now next step is to remove all html tags i can skip this step becuase my dataset doesnt contain any 

 # Remove Emojis & Special Characters is next step which isnt needed

#### Next Step in Data Cleaning : . Remove Stopwords

In [23]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rohit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [24]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [25]:
negation_words = {'no', 'not', 'nor', 'never'}

stop_words = stop_words - negation_words


def remove_stopwords(txt):
    return ' '.join(
        word for word in txt.split()
        if word not in stop_words
    )

df['tweets'] = df['tweets'].apply(remove_stopwords)

# split → check → keep → join


# The process of splitting text into tokens is called Tokenization

In [26]:
df.sample(5)

,tweets,labels
218483,explored chatgpt today concluded jobs safe 😂nchatgpt ai openaichatgpt openai,0
30767,think funniest thing chatgpt tendency equivocate presumably sources draws conflicting information doesnt know pick side,0
121375,20 entertaining uses chatgpt never knew possible,0
83065,chat chatgpt artificial intelligence designed imitate humantohuman conversation,0
10834,pace ai frightening chatgpt seems immensely powerful reduce jobs click button fact even threatens google search 👇,2

tweets    try talking chatgpt new ai system optimized dialogue feedback help us improve
labels                                                                                1
Name: 1, dtype: object