Business Understanding
        ↓
Data Collection
        ↓
Dataset Understanding
        ↓
Data Cleaning
        ↓
Handle Missing Values
        ↓
Handle Outliers (if required)
        ↓
Exploratory Data Analysis (EDA)
        ↓
Feature Engineering (if required)
        ↓
Encoding (if categorical data)
        ↓
Define Features (X) and Target (y)
        ↓
Train-Validation-Test Split
        ↓
Feature Scaling (Normalization / Standardization)
        ↓
Convert to Tensors
        ↓
Create Dataset & DataLoader
        ↓
Design Neural Network Architecture
        ↓
Choose Loss Function
        ↓
Choose Optimizer
        ↓
Training Loop
        ↓
Validation
        ↓
Hyperparameter Tuning
        ↓
Model Evaluation
        ↓
Save Trained Model
        ↓
Inference / Prediction
        ↓
Deployment
        ↓
GitHub + README

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
data = pd.read_csv(r"C:\Users\shobh\OneDrive\Attachments\Documents\Desktop\py\credit_card_frauds.csv")

df = pd.DataFrame(data)

In [3]:
df

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:44,"Heller, Gutmann and Zieme",grocery_pos,107.23,Orient,WA,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,49.159047,-118.186462,0
1,2019-01-01 00:00:51,Lind-Buckridge,entertainment,220.11,Malad City,ID,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,43.150704,-112.154481,0
2,2019-01-01 00:07:27,Kiehn Inc,grocery_pos,96.29,Grenada,CA,41.6125,-122.5258,589,Systems analyst,1945-12-21,413636e759663f264aae1819a4d4f231,41.657520,-122.230347,0
3,2019-01-01 00:09:03,Beier-Hyatt,shopping_pos,7.77,High Rolls Mountain Park,NM,32.9396,-105.8189,899,Naval architect,1967-08-30,8a6293af5ed278dea14448ded2685fea,32.863258,-106.520205,0
4,2019-01-01 00:21:32,Bruen-Yost,misc_pos,6.85,Freedom,WY,43.0172,-111.0292,471,"Education officer, museum",1967-08-02,f3c43d336e92a44fc2fb67058d5949e3,43.753735,-111.454923,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339602,2020-12-31 23:57:56,Schmidt-Larkin,home,12.68,Wales,AK,64.7556,-165.6723,145,"Administrator, education",1939-11-09,a8310343c189e4a5b6316050d2d6b014,65.623593,-165.186033,0
339603,2020-12-31 23:58:04,"Pouros, Walker and Spence",kids_pets,13.02,Greenview,CA,41.5403,-122.9366,308,Call centre manager,1958-09-20,bd7071fd5c9510a5594ee196368ac80e,41.973127,-123.553032,0
339604,2020-12-31 23:59:07,Reilly and Sons,health_fitness,43.77,Luray,MO,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,39.946837,-91.333331,0
339605,2020-12-31 23:59:15,Rau-Robel,kids_pets,86.88,Burbank,WA,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,46.658340,-119.715054,0
339606,2020-12-31 23:59:24,Breitenberg LLC,travel,7.99,Mesa,ID,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,44.470525,-117.080888,0

## <span style="color:#DC2626; font-family:Georgia;">Target Variable :</span>

- **<span style="color:#16A34A;">0</span>** → **<span style="color:#2563EB;">Legitimate Transaction</span>**
- **<span style="color:#DC2626;">1</span>** → **<span style="color:#EA580C;">Fraudulent Transaction</span>**

In [4]:
#data understandings


df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339607 entries, 0 to 339606
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  339607 non-null  object
 1   merchant               339607 non-null  object
 2   category               339607 non-null  object
 3   amt                    339607 non-null  float64
 4   city                   339607 non-null  object
 5   state                  339607 non-null  object
 6   lat                    339607 non-null  float64
 7   long                   339607 non-null  float64
 8   city_pop               339607 non-null  int64
 9   job                    339607 non-null  object
 10  dob                    339607 non-null  object
 11  trans_num              339607 non-null  object
 12  merch_lat              339607 non-null  float64
 13  merch_long             339607 non-null  float64
 14  is_fraud               339607 non-null  int64
dtypes: float64(5), int64(2), object(8)
memory usage: 38.9+ MB

In [5]:
df.isnull().sum()

trans_date_trans_time    0
merchant                 0
category                 0
amt                      0
city                     0
state                    0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

</span>**<span style="color:#2563EB;">No null values found</span>**

In [6]:
df.duplicated().sum()

np.int64(0)

</span>**<span style="color:#2563EB;">No duplicated rows found</span>**

In [7]:
df.nunique()

trans_date_trans_time    338504
merchant                    693
category                     14
amt                       32112
city                        176
state                        13
lat                         183
long                        183
city_pop                    174
job                         163
dob                         187
trans_num                339607
merch_lat                335608
merch_long               337263
is_fraud                      2
dtype: int64

In [8]:
df.sample()

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
71736,2019-06-27 17:26:32,"Hagenes, Kohler and Hoppe",food_dining,54.34,Rocky Mount,MO,38.2911,-92.7059,1847,Tax inspector,1988-10-26,4a4480bd020d14bdfedc625ed76046c1,38.946986,-92.871027,0

In [9]:
df.columns

Index(['trans_date_trans_time', 'merchant', 'category', 'amt', 'city', 'state',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'merch_lat',
       'merch_long', 'is_fraud'],
      dtype='object')

In [10]:
#data cleaning


df.drop(['trans_date_trans_time','dob','trans_num'],axis = 1,inplace=True)

In [11]:

df_cleaned = df.copy()

df_cleaned.to_csv(
    r"C:\Users\shobh\Downloads\AI and DATA SCIENCE\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀 (𝗧𝗮𝗯𝘂𝗹𝗮𝗿 𝗗𝗮𝘁𝗮)\Credit Card Fraud Detection\data\credit_card_frauds_cleaned.csv",
    index=False
)

#skiping eda for you claude 


make sevral observation write it in observations markdowan cell and use various html and .md syntax to make it colourful and good and also save all graphs here 

"C:\Users\shobh\Downloads\AI and DATA SCIENCE\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀\𝗗𝗲𝗲𝗽 𝗟𝗲𝗮𝗿𝗻𝗶𝗻𝗴 𝗣𝗿𝗼𝗷𝗲𝗰𝘁𝘀 (𝗧𝗮𝗯𝘂𝗹𝗮𝗿 𝗗𝗮𝘁𝗮)\Credit Card Fraud Detection\images"


and write observation and all colourful in box with professionalism

In [12]:
df.sample()

,merchant,category,amt,city,state,lat,long,city_pop,job,merch_lat,merch_long,is_fraud
4364,Corwin-Romague,travel,2.26,Ruidoso,NM,33.3305,-105.6933,8874,Licensed conveyancer,32.530481,-105.189792,0

In [13]:
#feature engineering 


X = df.drop(columns = ['is_fraud'])

y = df['is_fraud']

In [14]:
df

,merchant,category,amt,city,state,lat,long,city_pop,job,merch_lat,merch_long,is_fraud
0,"Heller, Gutmann and Zieme",grocery_pos,107.23,Orient,WA,48.8878,-118.2105,149,Special educational needs teacher,49.159047,-118.186462,0
1,Lind-Buckridge,entertainment,220.11,Malad City,ID,42.1808,-112.2620,4154,Nature conservation officer,43.150704,-112.154481,0
2,Kiehn Inc,grocery_pos,96.29,Grenada,CA,41.6125,-122.5258,589,Systems analyst,41.657520,-122.230347,0
3,Beier-Hyatt,shopping_pos,7.77,High Rolls Mountain Park,NM,32.9396,-105.8189,899,Naval architect,32.863258,-106.520205,0
4,Bruen-Yost,misc_pos,6.85,Freedom,WY,43.0172,-111.0292,471,"Education officer, museum",43.753735,-111.454923,0
...,...,...,...,...,...,...,...,...,...,...,...,...
339602,Schmidt-Larkin,home,12.68,Wales,AK,64.7556,-165.6723,145,"Administrator, education",65.623593,-165.186033,0
339603,"Pouros, Walker and Spence",kids_pets,13.02,Greenview,CA,41.5403,-122.9366,308,Call centre manager,41.973127,-123.553032,0
339604,Reilly and Sons,health_fitness,43.77,Luray,MO,40.4931,-91.8912,519,Town planner,39.946837,-91.333331,0
339605,Rau-Robel,kids_pets,86.88,Burbank,WA,46.1966,-118.9017,3684,Musician,46.658340,-119.715054,0
339606,Breitenberg LLC,travel,7.99,Mesa,ID,44.6255,-116.4493,129,Cartographer,44.470525,-117.080888,0

In [16]:
from sklearn.model_selection import train_test_split

X = df.drop("is_fraud", axis=1)
y = df["is_fraud"]

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

X_valid, X_test, y_valid, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

In [18]:
print("Training Set   :", X_train.shape)
print("Validation Set :", X_valid.shape)
print("Testing Set    :", X_test.shape)

print()

print("Training Labels   :", y_train.shape)
print("Validation Labels :", y_valid.shape)
print("Testing Labels    :", y_test.shape)

Training Set   : (237724, 11)
Validation Set : (50941, 11)
Testing Set    : (50942, 11)

Training Labels   : (237724,)
Validation Labels : (50941,)
Testing Labels    : (50942,)

In [21]:
categorical_columns = X_train.select_dtypes(include="object").columns

categorical_columns

numerical_columns = X_train.select_dtypes(include=["number"]).columns

numerical_columns

Index(['amt', 'lat', 'long', 'city_pop', 'merch_lat', 'merch_long'], dtype='object')

In [22]:
#encoding categorical column

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(
    handle_unknown="use_encoded_value",
    unknown_value=-1
)

X_train[categorical_columns] = encoder.fit_transform(
    X_train[categorical_columns]
)

X_valid[categorical_columns] = encoder.transform(
    X_valid[categorical_columns]
)

X_test[categorical_columns] = encoder.transform(
    X_test[categorical_columns]
)

In [24]:
#scaling 

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_valid = scaler.transform(X_valid)

X_test = scaler.transform(X_test)

In [25]:
X_train[:5]

array([[-0.31612137, -0.06281549, -0.39447962, -0.77309388, -1.15573471,
         0.37120211, -0.93892634, -0.36377417,  1.26960678,  0.19021714,
        -0.97311782],
       [ 1.68559059,  0.7066362 , -0.42338613, -1.59399994, -0.02623784,
        -0.22357082,  1.58517145, -0.05128218, -0.66370925, -0.05804641,
         1.54984605],
       [-0.96680193, -0.06281549,  0.03348528, -0.71152593, -1.15573471,
        -0.63069294, -0.74708093, -0.36535668, -0.92148472, -0.73182112,
        -0.73897867],
       [ 0.5183392 , -0.57578328, -0.19560036, -0.9783204 ,  0.5385106 ,
        -0.73113129,  0.35942584, -0.30326172, -0.27704605, -0.6707647 ,
         0.33432294],
       [-0.92706571,  0.7066362 , -0.38488538, -0.3010729 , -0.8733605 ,
        -0.01977464,  0.64242187, -0.36507142,  0.41035521, -0.19093242,
         0.66923087]])

In [27]:
#convert to tensors 


import torch

X_train = torch.tensor(X_train, dtype=torch.float32)
X_valid = torch.tensor(X_valid, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)

y_train = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
y_valid = torch.tensor(y_valid.values, dtype=torch.float32).view(-1, 1)
y_test = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

In [28]:
# Create Dataset & DataLoader

from torch.utils.data import TensorDataset

train_dataset = TensorDataset(X_train, y_train)
valid_dataset = TensorDataset(X_valid, y_valid)
test_dataset = TensorDataset(X_test, y_test)

In [29]:
#dataloader 

from torch.utils.data import DataLoader

train_loader = DataLoader(
    dataset=train_dataset,
    batch_size=64,shuffle=True)

valid_loader = DataLoader(
    dataset=valid_dataset,
    batch_size=64,shuffle=False)

test_loader = DataLoader(
    dataset=test_dataset,
    batch_size=64,
    shuffle=False
)

# Design Neural Network Architecture

problem is binary so outout feature will be 2 then lets check no. of input features

In [34]:
X_train.shape[1]

11

In [36]:
#we have 11 input features 

import torch.nn as nn

# we can use nn.Sequential here but i would like to go with class 

import torch
import torch.nn as nn


class FraudDetectionModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(11, 16)
        self.fc2 = nn.Linear(16, 8)
        self.fc3 = nn.Linear(8, 1)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.relu(x)
        x = self.fc3(x)

        return x


model = FraudDetectionModel()

In [37]:
print(model)

FraudDetectionModel(
  (fc1): Linear(in_features=11, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=8, bias=True)
  (fc3): Linear(in_features=8, out_features=1, bias=True)
  (relu): ReLU()
)

In [40]:
#now creating loss and optimiser

import torch.optim as optim

criterion = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(),lr=0.001)

In [44]:
model.parameters

<bound method Module.parameters of FraudDetectionModel(
  (fc1): Linear(in_features=11, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=8, bias=True)
  (fc3): Linear(in_features=8, out_features=1, bias=True)
  (relu): ReLU()
)>

Take One Batch
      ↓
Forward Pass
      ↓
Calculate Loss
      ↓
Clear Old Gradients
      ↓
Backward Pass
      ↓
Update Weights

In [60]:
#training loop

model.train()
epochs = 10

for epoch in range(epochs):
    epochs_loss = 0
    for X_batch, y_batch in train_loader:
        outputs = model(X_batch)
        loss = criterion(outputs, y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        epochs_loss = epochs_loss + loss.item()
    avg_loss = epochs_loss / len(train_loader)
    print(f"Epoch [{epoch+1}/{epochs}] | Loss: {avg_loss}")

Epoch [1/10] | Loss: 0.015236023865442117
Epoch [2/10] | Loss: 0.01523594045785944
Epoch [3/10] | Loss: 0.015133138677552794
Epoch [4/10] | Loss: 0.014985416050183099
Epoch [5/10] | Loss: 0.014863197508357054
Epoch [6/10] | Loss: 0.014717080246802535
Epoch [7/10] | Loss: 0.014657098902132447
Epoch [8/10] | Loss: 0.01457565621298037
Epoch [9/10] | Loss: 0.01447801045671702
Epoch [10/10] | Loss: 0.014445634333298995

| Epoch |   Loss |
| ----: | -----: |
|     1 | 0.0333 |
|     2 | 0.0215 |
|     3 | 0.0198 |
|     4 | 0.0181 |
|     5 | 0.0171 |
|     6 | 0.0166 |
|     7 | 0.0160 |
|     8 | 0.0158 |
|     9 | 0.0155 |
|    10 | 0.0154 |

In [ ]:
#next is model evaluation 


model.eval()