In [ ]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

Supervised Learning Workflow

Raw Data
    ↓
Cleaning

    ↓
Encoding

    ↓
X and y

    ↓
Train-Test Split

    ↓
Scaling

    ↓
Model

    ↓
Prediction
    ↓

Evaluation

Done

In [48]:
data = pd.read_csv(r"C:\Users\shobh\OneDrive\Attachments\Documents\Desktop\py\loan_approval_dataset.csv")

df = pd.DataFrame(data)

df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [ ]:
# cleaning data and prepare it for machine learning

df.isnull().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df.info()

In [56]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cols_to_encode = [' education', ' self_employed', ' loan_status']

for col in cols_to_encode:
    df[col] = le.fit_transform(df[col])


X = df[['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value',]]

y = df[[' loan_status']]

y

# 0 = Approved 1 = Rejecting

      loan_status
0               0
1               1
2               1
3               1
4               1
...           ...
4264            1
4265            0
4266            1
4267            0
4268            0

[4269 rows x 1 columns]

In [57]:
# now Features and Target Variable

# here we have to find Y = loan_status


X = df[['loan_id', ' no_of_dependents', ' education', ' self_employed',
       ' income_annum', ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value',]]

y = df[[' loan_status']]

y

      loan_status
0               0
1               1
2               1
3               1
4               1
...           ...
4264            1
4265            0
4266            1
4267            0
4268            0

[4269 rows x 1 columns]

In [58]:
# Train Test and Split

from sklearn.model_selection import train_test_split

X_train,X_test , y_train , y_test = train_test_split(X,y , test_size = 0.2, random_state = 42)

      loan_status
1703            1
1173            0
308             1
1322            0
3271            0
...           ...
912             0
443             0
1483            0
668             1
1114            1

[854 rows x 1 columns]

In [ ]:
# now scaling 

from sklearn.model_selection import StandardScaler

scaler = StandardScaler()

scaled_df = scaler.fit_transform()